export const musicData = [
    {
        id: 1,
        title: 'Birthday Song',
        artist: 'Davido',
        albumArt: 'https://images.pexels.com/photos/894156/pexels-photo-894156.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2016,
        requested: false,
        played: false,
    },
    {
        id: 2,
        title: 'Fine Lady',
        artist: 'wizkidayo',
        albumArt: 'https://images.unsplash.com/photo-1506010100053-cc98c49b6aa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8d2l6a2lkfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=700&q=60',
        year: 2020,
        requested: false,
        played: false,
    },
    {
        id: 3,
        title: 'Worries',
        artist: 'Tems',
        albumArt: 'https://images.pexels.com/photos/6862365/pexels-photo-6862365.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2021,
        requested: false,
        played: false,
    },
    {
        id: 4,
        title: 'Action Film',
        artist: 'M.I',
        albumArt: 'https://images.pexels.com/photos/8044178/pexels-photo-8044178.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2008,
        requested: false,
        played: false,
    },
    {
        id: 5,
        title: 'Pain Dem',
        artist: 'Tiwa Savage',
        albumArt: 'https://images.pexels.com/photos/4315839/pexels-photo-4315839.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2019,
        requested: false,
        played: false,
    },
    {
        id: 6,
        title: 'African giant',
        artist: 'Burna boy',
        albumArt: 'https://images.pexels.com/photos/1885213/pexels-photo-1885213.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2020,
        requested: false,
        played: false,
    },
    {
        id: 7,
        title: 'Sound',
        artist: 'Dunsin Oyekan',
        albumArt: 'https://images.pexels.com/photos/4406759/pexels-photo-4406759.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2020,
        requested: false,
        played: false,
    },
    {
        id: 8,
        title: 'Adonai',
        artist: 'Nathaniel Bassey',
        albumArt: 'https://images.pexels.com/photos/6953867/pexels-photo-6953867.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2020,
        requested: false,
        played: false,
    },
    {
        id: 9,
        title: 'unstoppable',
        artist: 'Lecrae',
        albumArt: 'https://images.pexels.com/photos/2489986/pexels-photo-2489986.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2018,
        requested: false,
        played: false,
    },
    {
        id: 10,
        title: 'Names of God',
        artist: 'Nathaniel Bassey',
        albumArt: 'https://images.pexels.com/photos/2403054/pexels-photo-2403054.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2021,
        requested: false,
        played: false,
    },
    {
        id: 11,
        title: 'Birthday Song',
        artist: 'Davido',
        albumArt: 'https://images.pexels.com/photos/894156/pexels-photo-894156.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2010,
        requested: false,
        played: false,
    },
    {
        id: 12,
        title: 'Fine Lady',
        artist: 'wizkidayo',
        albumArt: 'https://images.unsplash.com/photo-1506010100053-cc98c49b6aa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8d2l6a2lkfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=700&q=60',
        year: 2017,
        requested: false,
        played: false,
    },
    {
        id: 13,
        title: 'Worries',
        artist: 'Tems',
        albumArt: 'https://images.pexels.com/photos/6862365/pexels-photo-6862365.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2020,
        requested: false,
        played: false,
    },
    {
        id: 14,
        title: 'Action Film',
        artist: 'M.I',
        albumArt: 'https://images.pexels.com/photos/8044178/pexels-photo-8044178.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2008,
        requested: false,
        played: false,
    },
    {
        id: 15,
        title: 'Pain Dem',
        artist: 'Tiwa Savage',
        albumArt: 'https://images.pexels.com/photos/4315839/pexels-photo-4315839.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2010,
        requested: false,
        played: false,
    },
    {
        id: 16,
        title: 'African giant',
        artist: 'Burna boy',
        albumArt: 'https://images.pexels.com/photos/1885213/pexels-photo-1885213.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2021,
        requested: false,
        played: false,
    },
    {
        id: 17,
        title: 'Sound',
        artist: 'Dunsin Oyekan',
        albumArt: 'https://images.pexels.com/photos/4406759/pexels-photo-4406759.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2019,
        requested: false,
        played: false,
    },
    {
        id: 18,
        title: 'Adonai',
        artist: 'Nathaniel Bassey',
        albumArt: 'https://images.pexels.com/photos/6953867/pexels-photo-6953867.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2015,
        requested: false,
        played: false,
    },
    {
        id: 19,
        title: 'unstoppable',
        artist: 'Lecrae',
        albumArt: 'https://images.pexels.com/photos/2489986/pexels-photo-2489986.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2018,
        requested: false,
        played: false,
    },
    {
        id: 20,
        title: 'Names of God',
        artist: 'Nathaniel Bassey',
        albumArt: 'https://images.pexels.com/photos/2403054/pexels-photo-2403054.jpeg?auto=compress&cs=tinysrgb&w=400',
        year: 2020,
        requested: false,
        played: false,
    },
]